variable "Appname" {}
variable "min_size" {}                    
variable "max_size" {}
variable "desired_capacity" {}
variable "ami" {}               
variable "instance_type" {}            
variable "security_groups" {}            
variable "subnet1" {}                     
variable "subnet2" {}                    
variable "subnet3" {}                 